version: 2.1

orbs:
  kube: twdps/kube-ops@dev:alpha
  op: twdps/onepassword@3.0.0
  do: twdps/pipeline-events@5.4.0

globals:
  - &context platform
  - &executor-image ghcr.io/twplatformlabs/circleci-eks-ops:alpine-2026.06
  - &config-repo twplatformlabs/psk-aws-control-plane-configuration

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

commands:

  set-environment:
    description: generate environment credentials and configuration from templates
    parameters:
      cluster:
        description: access cluster for testing
        type: string
    steps:
      - op/env:
          env-file: op.<< parameters.cluster >>.env
      - kube/op-kubeconfig:
          op-value: platform/<< parameters.cluster>>/kubeconfig-base64
      - do/bash-functions

jobs:

  update istio deployment configuration:
    docker:
      - image: *executor-image
    parameters:
      cluster-role:
        description: cluster role to be updated
        type: string
    steps:
      - checkout
      - op/env
      - do/bash-functions
      - run:
          name: generate Application resource for istio namespaces/dependencies (syncWave 2)
          command: bash scripts/generate_istio_dependencies_application.sh << parameters.cluster-role >>
      - kube/write-to-github:
          source: deploy-files/istio-dependencies/*
          destination: "roles/<<parameters.cluster-role>>/istio-dependencies"
          repository-url: *config-repo
      - run:
          name: validate revision release request against current configuration
          command: bash scripts/validate_revision_settings.sh << parameters.cluster-role >>
      - run:
          name: generate Application resources for istio base (syncWave 3)
          command: bash scripts/generate_istio_base_application.sh << parameters.cluster-role >>
      - kube/write-to-github:
          source: deploy-files/istio-base/*
          destination: "roles/<<parameters.cluster-role>>/istio-base"
          repository-url: *config-repo
      - kube/write-to-github:
          source: deploy-files/istio-cni/*
          destination: "roles/<<parameters.cluster-role>>/istio-cni"
          repository-url: *config-repo

      - run:
          name: generate Application resources for istiod (syncWave 4)
          command: bash scripts/generate_istiod_application.sh << parameters.cluster-role >>
      - kube/write-to-github:
          source: deploy-files/istiod-staged/*
          destination: "roles/<<parameters.cluster-role>>/istiod-staged"
          repository-url: *config-repo
      - kube/write-to-github:
          source: deploy-files/istiod-release/*
          destination: "roles/<<parameters.cluster-role>>/istiod-release"
          repository-url: *config-repo

      - run:
          name: generate Application resources for revision tags (syncWave 5)
          command: bash scripts/generate_revision_tags.sh << parameters.cluster-role >>
      - kube/write-to-github:
          source: deploy-files/istio-revision-release/*
          destination: "roles/<<parameters.cluster-role>>/istio-revision-release"
          repository-url: *config-repo
      - kube/write-to-github:
          source: deploy-files/istio-revision-staged/*
          destination: "roles/<<parameters.cluster-role>>/istio-revision-staged"
          repository-url: *config-repo

      - run:
          name: generate Application resources for istio-ingressgateway (syncWave 6)
          command: bash scripts/generate_istio_ingressgateway_application.sh << parameters.cluster-role >>
      - kube/write-to-github:
          source: deploy-files/istio-ingressgateway/*
          destination: "roles/<<parameters.cluster-role>>/istio-ingressgateway"
          repository-url: *config-repo

  functional-tests:
    docker:
      - image: *executor-image
    parameters:
      cluster:
        description: cluster to test
        type: string
      cluster-role:
        description: cluster role to be updated
        type: string
    steps:
      - checkout
      - set-environment:
          cluster: << parameters.cluster >>
      - run:
          name: run integration test of istio service mesh
          command: bash scripts/integration_tests.sh << parameters.cluster >> << parameters.cluster-role >>

workflows:

  deploy sandbox role configuration:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - update istio deployment configuration:
          name: update sandbox istio configuration
          context: *context
          cluster-role: sandbox
          filters: *on-push-main

      - functional-tests:
          name: test sandbox cluster
          context: *context
          cluster: sbx-i01-aws-us-east-1
          cluster-role: sandbox
          requires:
            - update sandbox istio configuration
          filters: *on-push-main
  
  deploy production role configuration:
    jobs:
      - update istio deployment configuration:
          name: update production istio configuration
          context: *context
          cluster-role: production
          filters: *on-tag-main

      - functional-tests:
          name: test production cluster
          context: *context
          cluster: prod-i01-aws-us-east-2
          cluster-role: production
          requires:
            - update production istio configuration
          filters: *on-tag-main

  #     - do/gh-release:
  #         name: generate release notes
  #         context: *context
  #         notes-from-file: release.md
  #         include-commit-msg: true
  #         before-release:
  #           - op/env:
  #               env-file: op.prod-i01-aws-us-east-2.env
  #         requires:
  #           - test production cluster
  #         filters: *on-tag-main

  #     - do/schedule-pipeline:
  #         name: schedule nightly functional tests
  #         context: *context
  #         scheduled-pipeline-name: nightly observability operator functional test
  #         scheduled-pipeline-description: |
  #           Automatically triggers nightly run of functional-test job
  #         hours-of-day: "[1]"
  #         days-of-week: "[\"SUN\"]"
  #         before-schedule:
  #           - op/env:
  #               env-file: op.prod-i01-aws-us-east-2.env
  #         filters: *on-tag-main

  # run nightly integration test:
  #   when:
  #     equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
  #   jobs:
  #     - functional-tests:
  #         name: nightly sbx-i01-aws-us-east-1 functional test
  #         cluster: sbx-i01-aws-us-east-1
  #         cluster-role: sandbox
  #         context: *context
  #     - functional-tests:
  #         name: nightly prod-i01-aws-us-east-2 functional test
  #         cluster: prod-i01-aws-us-east-2
  #         cluster-role: production
  #         context: *context