---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system

---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress

---
apiVersion: v1
kind: Namespace
metadata:
  name: default-mtls    # test namespace for the current "release" revision
  labels:
    istio.io/rev: release
    platform-vault: "true"
    pod-security.kubernetes.io/enforce: baseline

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-mtls-ns-quota
  namespace: default-mtls
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "10"
    limits.memory: 20Gi

---
apiVersion: v1
kind: Namespace
metadata:
  name: default-mtls-staged   # test namespace for the pending "staged" revision
  labels:
    istio.io/rev: staged
    platform-vault: "true"
    pod-security.kubernetes.io/enforce: baseline

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-mtls-staged-ns-quota
  namespace: default-mtls-staged
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "10"
    limits.memory: 20Gi
